// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../layouts/components/Breadcrumb.vue')['default']
    DefaultBrand: typeof import('./../layouts/components/DefaultBrand.vue')['default']
    DefaultHeader: typeof import('./../layouts/DefaultHeader.vue')['default']
    DefaultLayout: typeof import('./../layouts/DefaultLayout.vue')['default']
    DefaultMenu: typeof import('./../layouts/components/DefaultMenu.vue')['default']
    DefaultTabs: typeof import('./../layouts/DefaultTabs.vue')['default']
    HeaderController: typeof import('./../layouts/components/HeaderController.vue')['default']
    NaiveProvider: typeof import('./../layouts/NaiveProvider.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NMenu: typeof import('naive-ui')['NMenu']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterEntry: typeof import('./../layouts/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemePanel: typeof import('./../layouts/components/ThemePanel.vue')['default']
    ThemeSettingPanel: typeof import('./../layouts/components/ThemeSettingPanel.vue')['default']
    ToggleCollapsed: typeof import('./../layouts/components/ToggleCollapsed.vue')['default']
  }
}
